export const SET_LOADING = 'SET_LOADING'
export const SET_NOT_LOADING = 'SET_NOT_LOADING'
export const SET_USER = 'SET_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const SET_ERROR = 'SET_ERROR'
export const UNSET_ERROR = 'UNSET_ERROR'